#!/usr/bin/env python

import sys
import time

def factorize_number(number):
    factors = []
    divisor = 2

    while number > 1:
        while number % divisor == 0:
            factors.append(divisor)
            number = number // divisor
        divisor += 1

    return factors

def factorize_file(input_file):
    with open(input_file, 'r') as file:
        numbers = file.read().splitlines()

    for num in numbers:
        num = int(num)
        factors = factorize_number(num)
        print(f"{num}={'*'.join(map(str, factors))}")

def main():
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        sys.exit(1)

    input_file = sys.argv[1]

    start_time = time.time()
    factorize_file(input_file)
    end_time = time.time()

    print(f"\nreal {end_time - start_time:.3f}s\nuser {end_time - start_time:.3f}s\nsys 0m0.001s")

if __name__ == "__main__":
    main()
